### ISSUE TITLE
[Enhancement]: Fix order in the Releases navigation

### ISSUE THREAD

**Issue by 3manuek** [babelfish-for-postgresql/babelfish_project_website#205]
### Describe how this change will improve the Babelfish website.

Right now, [Just the Docs does not implement customizable ordering](https://github.com/just-the-docs/just-the-docs/issues/654#issuecomment-849551186).

### Share implementation details for the website enhancement.

There are two ways probably:

- Customize the ordering _outside_ the just_the_docs.
- Add a `_config.yml` section with the specific `nav_order`, like:

```yaml
defaults:
  -
    scope: {path: docs, type: pages}
    values: {layout: default}
  - 
    scope: {path: "docs/chapter10"}
    values: {nav_order: 10}
  - 
    scope: {path: "docs/chapter1"}
    values: {nav_order: 1}
  - 
... 
```

### Relevant documentation

```shell
- [Ordering pages](https://alexunder.github.io/docs/navigation-structure/#ordering-pages)
- [Implementing nav_order from `config.yml`](https://github.com/just-the-docs/just-the-docs/issues/654#issuecomment-849551186)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
